# Theoretical Questions:

In [1]:
import numpy as np

In [2]:
## reversing a 1d array

one_arr=np.array([1,2,3,4,5])
one_arr[::-1]

array([5, 4, 3, 2, 1])

In [3]:
## reversing a 2d array

#rowwise
two_arr=np.array([[1,2,3],[4,5,6]])
two_arr[::-1, :]

array([[4, 5, 6],
       [1, 2, 3]])

In [4]:
## columnwise
two_arr=np.array([[1,2,3],[4,5,6]])
two_arr[:,::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [5]:
## changing dtype of the array

data=np.array([1,2,3])
data.dtype

dtype('int32')

In [6]:
## changing dtype of the array

data=data.astype(float)
data ## converted into a float value

array([1., 2., 3.])

Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Ans. ndarray (N-dimensional array) is the fundamental data structure used to represent multi-dimensional arrays of fixed-size elements, all of which are of the same data type. It is highly efficient for numerical operations and forms the core of scientific computing in Python.

Some Features of ndarray
-- Multi-dimensional: An ndarray can represent arrays with any number of dimensions (1D, 2D, 3D, etc.).
-- Efficient Memory Layout: ndarray stores elements in contiguous blocks of memory, ensuring efficient access and manipulation.
--Homogeneous Data Type:All elements in an ndarray must be of the same data type (e.g., integers, floats). This makes operations faster and more memory-efficient compared to Python lists, which can hold mixed data types.

difference between ndarray and python list
ndarray:
--Homogeneous (all elements are of the same type)	Heterogeneous (can contain mixed types)
--	Fixed size after creation	
--	Fast and memory-efficient due to contiguous storage and vectorized operations	
--Built-in support for multi-dimensional arrays	
pyhton list:
--Heterogeneous (can contain mixed types)
--Dynamically resizable
--Slower for numerical operations, especially with ------large datasets
--No native support for multi


In [7]:
#vstack()  on 1d array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# hstack() 0n 2d array
arr1=np.array([[1,2,3], [8,4,7]])
arr2=np.array([[4,5,6],[24,45,78]])
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  4,  7, 24, 45, 78]])

In [9]:
 #fliplr() (Flip Left-to-Right)

arr= np.array([[1, 2, 3],[4, 5, 6]])
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4]])

In [10]:
# flipud() (Flip Up-to-Down)

arr= np.array([[1, 2, 3],[4, 5, 6]])
np.flipud(arr)

array([[4, 5, 6],
       [1, 2, 3]])

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sub_arrays = np.array_split(arr, 4)
sub_arrays

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Vectorized addition
a + b


array([ 6,  8, 10, 12])

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Broadcasting operation
a + b

array([[11, 22, 33],
       [14, 25, 36]])

# Practical Questions:

In [14]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
#Ans...
arr=np.random.randint(1,100, (3,3))
arr

array([[93, 31, 33],
       [53,  6, 74],
       [84, 66, 28]])

In [15]:
arr.T

array([[93, 53, 84],
       [31,  6, 66],
       [33, 74, 28]])

In [16]:
#Q2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
#sol.
arr1=np.random.randint(1,10,10)
arr1

array([1, 9, 2, 1, 7, 7, 4, 4, 1, 9])

In [17]:
arr1.reshape((2,5))

array([[1, 9, 2, 1, 7],
       [7, 4, 4, 1, 9]])

In [18]:
arr1.reshape((5,2))

array([[1, 9],
       [2, 1],
       [7, 7],
       [4, 4],
       [1, 9]])

In [19]:
# Q3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
## sol.
arr2=np.random.randint(1,9, (4,4)).astype(float)
arr2

array([[5., 3., 1., 2.],
       [8., 6., 3., 2.],
       [2., 2., 3., 3.],
       [7., 3., 6., 1.]])

In [20]:
bordered_array = np.pad(arr2, pad_width=1, mode='constant', constant_values=0)
bordered_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 5., 3., 1., 2., 0.],
       [0., 8., 6., 3., 2., 0.],
       [0., 2., 2., 3., 3., 0.],
       [0., 7., 3., 6., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
np.arange(10,60, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [22]:
#Q5. . Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

arr3=np.array(['python', 'numpy', 'pandas'])
arr3[0].upper()


'PYTHON'

In [23]:
arr3[1].lower()

'numpy'

In [24]:
arr3[2].title()

'Pandas'

In [25]:
arr3[0].capitalize()

'Python'

In [26]:
#Q6  Generate a NumPy array of words. Insert a space between each character of every word in the array
#sol. 
arr4=np.array(['pencil', 'books', 'sharpner', 'ruller'])
spaced_array=np.array([' '.join(i) for i in arr4])
spaced_array

array(['p e n c i l', 'b o o k s', 's h a r p n e r', 'r u l l e r'],
      dtype='<U15')

In [27]:
#Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
#sol.
a1=np.array([[1,2,3], [4,5,6]])
a2=np.array([[3,6,13], [14,51,2]])

In [28]:
a1+a2

array([[ 4,  8, 16],
       [18, 56,  8]])

In [29]:
a1-a2

array([[ -2,  -4, -10],
       [-10, -46,   4]])

In [30]:
a1/a2

array([[0.33333333, 0.33333333, 0.23076923],
       [0.28571429, 0.09803922, 3.        ]])

In [31]:
a1*a2

array([[  3,  12,  39],
       [ 56, 255,  12]])

In [32]:
#Q8  . Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
#sol.

id_mat=np.eye(5)
id_mat


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.diag(id_mat)

array([1., 1., 1., 1., 1.])

In [34]:
#Q9  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
# sol. 
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

arr5=np.random.randint(1,1000, 100)
prime=np.array([num for num in arr5 if is_prime(num)])
prime

array([ 43, 229, 193, 149, 127, 997, 911, 859, 181, 557, 971,  79, 107,
       491, 113, 149,   2, 383, 499, 907, 503])

In [35]:
#Q10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averagres
#sol.

daily_temp = np.random.uniform(0, 30, size=30)
daily_temp

weekly_temp=daily_temp.reshape(6,5)

weekly_average=np.mean(weekly_temp)

weekly_average

13.844976537503076